
name: 'dbt_insightflow'
version: '1.0.0'
profile: 'insightflow_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_insightflow:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: marts
      core:
        +materialized: incremental
      kpi:
        +materialized: view