insightflow_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: insightflow-analytics-489617
      dataset: dbt
      threads: 4
      timeout_seconds: 300
      location: EU