name: InsightFlow Daily Pipeline

on:
  push:
    branches: [ main ] # Se activa cada vez que subes cambios
  workflow_dispatch:   # Esto te permite darle a un botón de "Play" manual

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Run Orchestrator
        run: python orchestrator.py